<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default Suite" duration-ms="49" started-at="2018-01-22T07:38:42Z" finished-at="2018-01-22T07:38:42Z">
    <groups>
    </groups>
    <test name="TestngPro" duration-ms="49" started-at="2018-01-22T07:38:42Z" finished-at="2018-01-22T07:38:42Z">
      <class name="com.dong.testng.test.MathTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.dong.testng.test.MathTest@18e8568]" name="setUp" is-config="true" duration-ms="18" started-at="2018-01-22T15:38:42Z" finished-at="2018-01-22T15:38:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testFactorial()[pri:0, instance:com.dong.testng.test.MathTest@18e8568]" name="testFactorial" duration-ms="4" started-at="2018-01-22T15:38:42Z" finished-at="2018-01-22T15:38:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [6] but found [5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [6] but found [5]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.dong.testng.test.MathTest.testFactorial(MathTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFactorial -->
        <test-method status="PASS" signature="testFactorial2()[pri:0, instance:com.dong.testng.test.MathTest@18e8568]" name="testFactorial2" duration-ms="0" started-at="2018-01-22T15:38:42Z" finished-at="2018-01-22T15:38:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFactorial2 -->
        <test-method status="SKIP" signature="testFactorial1()[pri:0, instance:com.dong.testng.test.MathTest@18e8568]" name="testFactorial1" duration-ms="0" started-at="2018-01-22T15:38:42Z" depends-on-methods="com.dong.testng.test.MathTest.testFactorial" finished-at="2018-01-22T15:38:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MathTest.testFactorial1()[pri:0, instance:com.dong.testng.test.MathTest@18e8568] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MathTest.testFactorial1()[pri:0, instance:com.dong.testng.test.MathTest@18e8568] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1068)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFactorial1 -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:com.dong.testng.test.MathTest@18e8568]" name="endTest" is-config="true" duration-ms="1" started-at="2018-01-22T15:38:42Z" finished-at="2018-01-22T15:38:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- com.dong.testng.test.MathTest -->
    </test> <!-- TestngPro -->
  </suite> <!-- Default Suite -->
</testng-results>
